-- SGR Moulds India — Work Order Workbench: database schema
-- Run once in Supabase: Dashboard -> SQL Editor -> New query -> paste -> Run.
-- Safe to re-run: every statement is idempotent.
--
-- Design: a fixed "core" of columns we filter / total on, plus a `data` jsonb column on each
-- table for every other field. A new field in the app lands in `data` automatically, so adding
-- or removing a field never needs a database change (see storage.js for the app-side rules).

-- ---------------------------------------------------------------- tables

create table if not exists public.work_orders (
  uid              uuid primary key,              -- generated by the app, stable for life
  order_no         text not null,                 -- business number, e.g. "343/2026-27" (editable)
  status           text not null default 'DRAFT',
  vendor_code      text,
  issue_date       text,                          -- text: the app currently mixes dd/mm/yyyy and yyyy-mm-dd
  delivery_target  text,
  data             jsonb not null default '{}'::jsonb,   -- all other header fields
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  created_by       uuid default auth.uid(),
  updated_by       uuid default auth.uid()
);

create table if not exists public.work_order_items (
  order_uid   uuid not null references public.work_orders(uid) on delete cascade,
  item_id     text not null,                      -- the app's line-item id, unique within an order
  position    integer not null default 0,         -- keeps the line order the user sees
  part_no     text,
  qty         numeric not null default 0,
  length_mm   numeric not null default 0,
  weight      numeric not null default 0,
  price       numeric not null default 0,
  data        jsonb not null default '{}'::jsonb, -- description, uom, category, remarks, ...
  primary key (order_uid, item_id)
);

create table if not exists public.audit_steps (
  order_uid   uuid not null references public.work_orders(uid) on delete cascade,
  step_id     integer not null,                   -- 1 Prepared, 2 Verified, 3 GM/JMD, 4 Dispatch
  role        text,
  person      text,                               -- name typed on the sign-off form
  status      text,
  verified    boolean not null default false,
  time        text,                               -- display string shown in the app
  signed_by   uuid,                               -- login that pressed "sign" (set by the server)
  signed_at   timestamptz,                        -- when (set by the server, not editable from the app)
  data        jsonb not null default '{}'::jsonb,
  primary key (order_uid, step_id)
);

create index if not exists work_orders_order_no_idx on public.work_orders (order_no);
create index if not exists work_orders_created_at_idx on public.work_orders (created_at);

-- Any direct edit (e.g. in the dashboard) also bumps updated_at.
create or replace function public.touch_work_order() returns trigger
language plpgsql as $$
begin
  new.updated_at := now();
  new.updated_by := auth.uid();
  return new;
end $$;

drop trigger if exists work_orders_touch on public.work_orders;
create trigger work_orders_touch before update on public.work_orders
  for each row execute function public.touch_work_order();

-- ---------------------------------------------------------------- access rules (RLS)
-- Only signed-in users can read or write anything. The public "anon" key that ships in the
-- website therefore cannot read a single row without a login.
-- Every signed-in user currently has full access. To restrict by role later, replace the
-- `using (true)` conditions below (e.g. only a "gm" role may set step 3 verified).

alter table public.work_orders       enable row level security;
alter table public.work_order_items  enable row level security;
alter table public.audit_steps       enable row level security;

do $$
declare t text;
begin
  foreach t in array array['work_orders', 'work_order_items', 'audit_steps'] loop
    execute format('drop policy if exists "signed-in users full access" on public.%I', t);
    execute format(
      'create policy "signed-in users full access" on public.%I for all to authenticated using (true) with check (true)', t);
  end loop;
end $$;

-- ---------------------------------------------------------------- save function
-- The app saves one whole order per call (header + items + sign-off steps) in ONE transaction.
--
-- Conflict protection: the app sends the `updated_at` it last saw (expected_updated_at). If someone
-- else saved the order since, this raises 'CONFLICT' instead of silently overwriting their work.
-- Sign-off stamping: signed_by / signed_at are set here, by the server, at the moment a step flips
-- to verified. They cannot be forged from the browser.

create or replace function public.save_work_order(p jsonb) returns timestamptz
language plpgsql
security invoker
as $$
declare
  v_uid      uuid := (p->>'uid')::uuid;
  v_existing timestamptz;
  v_saved    timestamptz;
begin
  select updated_at into v_existing from public.work_orders where uid = v_uid for update;
  -- compared to the millisecond so a client that keeps only millisecond precision never false-alarms
  if found and (p->>'expected_updated_at' is null
                or date_trunc('milliseconds', v_existing)
                   <> date_trunc('milliseconds', (p->>'expected_updated_at')::timestamptz)) then
    raise exception 'CONFLICT' using errcode = 'P0001';
  end if;

  insert into public.work_orders as w (uid, order_no, status, vendor_code, issue_date, delivery_target, data)
  values (v_uid, p->>'order_no', coalesce(p->>'status', 'DRAFT'), p->>'vendor_code',
          p->>'issue_date', p->>'delivery_target', coalesce(p->'data', '{}'::jsonb))
  on conflict (uid) do update set
    order_no        = excluded.order_no,
    status          = excluded.status,
    vendor_code     = excluded.vendor_code,
    issue_date      = excluded.issue_date,
    delivery_target = excluded.delivery_target,
    data            = excluded.data
  returning w.updated_at into v_saved;

  -- line items: remove the ones the user deleted, then upsert the rest in order
  delete from public.work_order_items
   where order_uid = v_uid
     and item_id not in (select x->>'item_id' from jsonb_array_elements(coalesce(p->'items', '[]'::jsonb)) x);

  insert into public.work_order_items as i (order_uid, item_id, position, part_no, qty, length_mm, weight, price, data)
  select v_uid, x->>'item_id', (t.ord - 1)::int, x->>'part_no',
         coalesce((x->>'qty')::numeric, 0), coalesce((x->>'length_mm')::numeric, 0),
         coalesce((x->>'weight')::numeric, 0), coalesce((x->>'price')::numeric, 0),
         coalesce(x->'data', '{}'::jsonb)
    from jsonb_array_elements(coalesce(p->'items', '[]'::jsonb)) with ordinality as t(x, ord)
  on conflict (order_uid, item_id) do update set
    position  = excluded.position,
    part_no   = excluded.part_no,
    qty       = excluded.qty,
    length_mm = excluded.length_mm,
    weight    = excluded.weight,
    price     = excluded.price,
    data      = excluded.data;

  -- sign-off steps
  delete from public.audit_steps
   where order_uid = v_uid
     and step_id not in (select (x->>'step_id')::int from jsonb_array_elements(coalesce(p->'audit_steps', '[]'::jsonb)) x);

  insert into public.audit_steps as s (order_uid, step_id, role, person, status, verified, time, signed_by, signed_at, data)
  select v_uid, (x->>'step_id')::int, x->>'role', x->>'person', x->>'status',
         coalesce((x->>'verified')::boolean, false), x->>'time',
         case when coalesce((x->>'verified')::boolean, false) then auth.uid() end,
         case when coalesce((x->>'verified')::boolean, false) then now() end,
         coalesce(x->'data', '{}'::jsonb)
    from jsonb_array_elements(coalesce(p->'audit_steps', '[]'::jsonb)) x
  on conflict (order_uid, step_id) do update set
    role      = excluded.role,
    person    = excluded.person,
    status    = excluded.status,
    verified  = excluded.verified,
    time      = excluded.time,
    data      = excluded.data,
    -- keep the original signer/time while it stays verified; clear when un-verified
    signed_by = case when not excluded.verified then null
                     when s.verified then s.signed_by else auth.uid() end,
    signed_at = case when not excluded.verified then null
                     when s.verified then s.signed_at else now() end;

  return v_saved;
end $$;

revoke all on function public.save_work_order(jsonb) from public, anon;
grant execute on function public.save_work_order(jsonb) to authenticated;
